global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
    metrics_path: '/metrics'

  - job_name: 'profile-service'
    static_configs:
      - targets: ['profile-service:3002']
    metrics_path: '/metrics'

  - job_name: 'calendar-service'
    static_configs:
      - targets: ['calendar-service:3003']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 